#!/bin/bash

# settings local to current system

export JAVA_HOME="/usr/lib/jvm/java-6-sun"
# export JAVA_HOME="/usr/java/latest/"
export PATH="/sbin:/usr/sbin:$JAVA_HOME/bin:$PATH:$HOME/bin"
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/i386/server:$LD_LIBRARY_PATH

